// examples/react-ui-components/src/pages/Home.tsx
import React from 'react'

import { Guard, GuardLocalConfig, User } from '@authing/react-ui-components'

import '@authing/react-ui-components/dist/esm/guard.min.css'

import * as facePlugin from 'face-api.js'

export default function Home () {
  const appId = 'AUTHING_APP_ID'

  const config: Partial<GuardLocalConfig> = {
    lang: 'en-US'
  }

  const onLogin = (userInfo: User) => {
    console.log(userInfo)
  }

  return <Guard
    appId={appId}
    onLogin={onLogin}
    visible={true}
    config={config}
    facePlugin={facePlugin}
  />
}

// examples/vue-ui-components/vue3/src/views/Home.vue
<template>
  <div class="home-container">
    <Guard :appId="appId" @login="onLogin"></Guard>
  </div>
</template>

<script lang="ts" scoped>
import { defineComponent } from 'vue'

import { Guard } from '@authing/vue-ui-components'

import '@authing/vue-ui-components/dist/esm/guard.min.css'

import type { User } from '@authing/vue-ui-components'

export default defineComponent({
  components: {
    Guard
  },
  setup () {
    const appId = 'AUTHING_APP_ID'

    const onLogin = (userInfo: User) => {
      console.log(userInfo)
    }

    return {
      appId,
      onLogin
    }
  }
})
</script>
