// examples/guard-vue3/src/views/Callback.vue
<template>
  <div class="callback-container">
    <div>{{ message }}</div>
  </div>
</template>

<script scoped setup>
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'

import { useGuard } from '@authing/guard-vue3'

const router = useRouter()

const guard = useGuard()

const message = 'This is callback page ~'

const handleAuthingLoginCallback = async () => {
  await guard.handleRedirectCallback()
  router.replace({
    name: 'Personal'
  })
}

onMounted(() => {
  handleAuthingLoginCallback()
})
</script>

// examples/guard-react/src/pages/Callback.tsx
import React, { useEffect } from 'react'
import { useHistory } from 'react-router-dom'

import { useGuard } from '@authing/guard-react'

export default function Callback() {
  const history = useHistory()
  const guard = useGuard()

  const handleCallback = async () => {
    await guard.handleRedirectCallback()
    history.replace('/personal')
  }

  useEffect(() => {
    handleCallback()
  })

  return <div>This is Callback page</div>
}
