// packages/guard-vue3/example/src/views/Login.vue
<template>
  <div class="login-container">
    <div style="margin-bottom: 30px;">
      <button v-if="!userInfo" @click="onLogin">登录</button>
      <button v-else @click="onLogout">登出</button>
    </div>

    <div v-if="userInfo">
      <div>用户信息：</div>
      <textarea cols="100" rows="30" :value="userInfo"></textarea>
    </div>
  </div>
</template>

<script setup scoped>
import { ref, onMounted } from 'vue'

import { useAuthing } from '../../../dist/esm/guard.min.js'

const $authing = useAuthing()
const userInfo = ref('')

const getCurrentUser = async () => {
  const _userInfo = await $authing.guard.trackSession()
  userInfo.value = _userInfo && JSON.stringify(_userInfo, null, 2) || ''
}
const onLogin = () => $authing.guard.startWithRedirect()
const onLogout = () => $authing.guard.logout()

onMounted(() => {
  getCurrentUser()
})
</script>

// examples/guard-angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core'

import { GuardService } from '@authing/guard-angular'

@Component({
  selector: 'login-container',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  constructor (
    private authing: GuardService
  ) {}

  userInfo = ''

  ngOnInit () {
    this.getCurrentUser()
  }

  onLogin () {
    this.authing.client.startWithRedirect()
  }

  onLogout () {
    this.authing.client.logout()
  }

  async getCurrentUser () {
    const _userInfo = await this.authing.client.authClient.getCurrentUser()
    this.userInfo = _userInfo && JSON.stringify(_userInfo, null, 2) || ''
  }
}

<div class="login-container">
  <div style="margin-bottom: 30px;">
    <button *ngIf="!userInfo" (click)="onLogin()">登录</button>
    <button *ngIf="userInfo" (click)="onLogout()">登出</button>
  </div>

  <div *ngIf="userInfo">
    <div>用户信息：</div>
    <textarea cols="100" rows="30" [value]="userInfo"></textarea>
  </div>
</div>
