// examples/guard-vue2/src/views/Home.vue
<template>
  <div class="home-container">
    <div style="margin-bottom: 30px;">{{ message }}</div>
    <button @click="toLogin">go to login page</button>
    <div id="home-container"></div>
  </div>
</template>

<script scoped>
export default {
  data () {
    return {
      message: 'This is Home page'
    }
  },
  mounted () {
    console.log('this.$guard: ', this.$guard)
  },
  methods: {
    toLogin () {
      this.$router.push({
        name: 'Login'
      })
    }
  }
}
</script>

// examples/guard-angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'home-container',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor (
    private router: Router
  ) {}
  title = 'This is Home page'

  toLogin () {
    this.router.navigateByUrl('login')
  }
}

<div class="home-container">
  <div>{{ title }}</div>
  <button (click)="toLogin()">go to login page</button>
</div>
