// examples/guard-vue2/src/views/Personal.vue
<template>
  <div class="personal-container">
    <div>{{ message }}</div>
    <textarea id="" cols="100" rows="30" :value="userInfo"></textarea>
  </div>
</template>

<script scoped>
export default {
  data () {
    return {
      message: 'This is Personal page ~~',
      userInfo: ''
    }
  },
  created () {
    this.getUserInfo()
  },
  methods: {
    getUserInfo () {
      this.$authing.guard.trackSession().then(res => {
        this.userInfo = JSON.stringify(res || '', null, 2)
      })
    }
  }
}
</script>

// packages/react-guard/example/src/pages/Personal.tsx
import React, { useState } from 'react'
import { useAuthing } from '@authing/react-guard'

export default function Personal() {
  const [userInfo, setUserInfo] = useState('')

  const guard = useAuthing()

  guard.trackSession().then(res => {
    console.log('trackSession res: ', res)
    setUserInfo(JSON.stringify(res, null, 2))
  })

  const onLogout = () => guard.logout()

  return (
    <div>
      <div>
        <button onClick={onLogout}>登出</button>
      </div>
      {userInfo && (
        <div>
          <div>用户信息：</div>
          <textarea cols={100} rows={30} defaultValue={userInfo}></textarea>
        </div>
      )}
    </div>
  )
}
