// examples/guard-vue2/normal/src/views/Personal.vue
<template>
  <div class="personal-container">
    <div>{{ message }}</div>
    <div>
      <button class="authing-button" @click="logout">Logout</button>
      <button class="authing-button" @click="updateProfile">Update Profile</button>
    </div>
    <textarea id="" cols="100" rows="30" :value="userInfo"></textarea>
  </div>
</template>

<script>
export default {
  data () {
    return {
      message: 'This is Personal page ~~',
      userInfo: ''
    }
  },
  created () {
    this.getUserInfo()
  },
  methods: {
    async getUserInfo () {
      const userInfo = await this.$guard.trackSession()
      this.userInfo = JSON.stringify(userInfo, null, 2)
    },
    // 登出后的回调地址请在 Authing 控制台「应用详情」-「应用配置」-「登出回调 URL」中配置
    logout () {
      this.$guard.logout()
    },
    async updateProfile() {
      const authenticationClient = await this.$guard.getAuthClient()

      // 获取到 AuthenticationClient 实例之后，可以调用其提供的所有方法
      // 比如更新用户昵称
      const userProfile = await authenticationClient.updateProfile({
        nickname: 'Nickaaa'
      })

      console.log(userProfile)

      // 更多 AuthenticationClient 的方法，请见 authing-js-sdk 文档介绍。
    }
  }
}
</script>
<style scoped>
.authing-button {
  margin-bottom: 10px;
  margin-right: 10px;
}
</style>

// examples/guard-angular/normal/src/app/pages/personal/personal.component.ts
import { Component } from '@angular/core'
import { AuthenticationClient, GuardService, User } from '@authing/guard-angular'

@Component({
  selector: 'personal-container',
  templateUrl: './personal.component.html',
  styleUrls: ['./personal.component.css']
})
export class PersonalComponent {
  constructor(private guard: GuardService) {}

  userInfo = ''

  ngOnInit() {
    this.getUserInfo()
  }

  // 登出后的回调地址请在 Authing 控制台「应用详情」-「应用配置」-「登出回调 URL」中配置
  logout() {
    this.guard.client.logout()
  }

  async getUserInfo() {
    const _userInfo: User | null = await this.guard.client.trackSession()
    this.userInfo = JSON.stringify(_userInfo || '', null, 2)
  }

  async updateProfile() {
    const authenticationClient: AuthenticationClient = await this.guard.client.getAuthClient()

    // 获取到 AuthenticationClient 实例之后，可以调用其提供的所有方法
    // 比如更新用户昵称
    const userProfile: User = await authenticationClient.updateProfile({
      nickname: 'Nick'
    })

    console.log('userProfile: ', userProfile)

    // 更多 AuthenticationClient 的方法，请见 authing-js-sdk 文档介绍。
  }
}

<div class="personal-container">
  <div>
    <button class="authing-button" (click)="logout()">Logout</button>
    <button class="authing-button" (click)="updateProfile()">updateProfile</button>
  </div>
  <textarea cols="100" rows="30">{{ userInfo }}</textarea>
</div>
