// examples/guard-vue3/modal/src/views/Embed.vue
<template>
  <div class="embed-container">
    <button @click="showGuard">Show Guard</button>

    <div>模态窗口打开后会在 2 秒内调用 hide 方法关闭模态窗口，用于展示 hide 方法的效果</div>
    <div>模态框自动关闭后，可以点击 Show Guard 按钮再次显示</div>

    <div id="authing-guard-container"></div>
  </div>
</template>

<script scoped setup>
import { onMounted } from 'vue'

import { useGuard } from '@authing/guard-vue3'

const guard = useGuard()

const showGuard = () => guard.show()

onMounted(() => {
  guard.start('#authing-guard-container').then(userInfo => {
    console.log('userInfo: : ', userInfo)
  })

  setTimeout(() => {
    guard.hide()
  }, 2000)
})
</script>

// examples/guard-react18/modal/src/pages/Embed.tsx
import React, { useEffect } from 'react'

import { useGuard, User } from '@authing/guard-react18'

export default function Embed() {
  const guard = useGuard()

  const showGuard = () => guard.show()

  useEffect(() => {
    // 挂载模态框，当用户完成登录之后，你可以获取到用户信息
    guard.start('#authing-guard-container').then((userInfo: User) => {
      console.log('userInfo: ', userInfo)

      setTimeout(() => {
        guard.hide()
      }, 2000)
    })
  }, [])

  return <div>
    <button className='authing-button' onClick={showGuard}>Show Guard</button>

    <div>模态窗口打开并登录成功后会在 2 秒内调用 hide 方法关闭模态窗口，用于展示 hide 方法的效果</div>
    <div>模态框自动关闭后，可以点击 Show Guard 按钮再次显示</div>

    <div id="authing-guard-container"></div>
  </div>
}
