// examples/guard-react18/normal/src/pages/Home.tsx
import React from 'react'
import { useHistory } from 'react-router-dom'

export default function Home() {
  const history = useHistory()

  const toEmbed = () => history.push('/embed')
  const toJump = () => history.push('/jump')

  return (
    <div>
      <div style={{ marginBottom: '20px' }} onClick={toEmbed}>
        <button className='authing-button'>嵌入模式 - 普通形态</button>
      </div>
      <div>
        <button className='authing-button' onClick={toJump}>托管模式</button>
      </div>
    </div>
  )
}

// examples/guard-vue2/normal/src/views/Home.vue
<template>
  <div class="home-container">
    <div style="margin-bottom: 20px;">
      <button @click="toEmbed">嵌入模式 - 普通形态</button>
    </div>
    <div>
      <button @click="toJump">托管模式</button>
    </div>
  </div>
</template>

<script scoped>
export default {
  data () {
    return {}
  },
  methods: {
    toEmbed () {
      this.$router.push({
        name: 'Embed'
      })
    },
    toJump () {
      this.$router.push({
        name: 'Jump'
      })
    }
  }
}
</script>
