// examples/guard-angular/normal/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router';

@Component({
  selector: 'home-container',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {
  constructor (
    private router: Router
  ) {}

  toEmbed () {
    this.router.navigateByUrl('embed')
  }

  toJump () {
    this.router.navigateByUrl('jump')
  }
}

<div class="home-container">
  <button class="authing-button" (click)="toEmbed()">嵌入模式 - 普通形态</button>
  <button class="authing-button" (click)="toJump()">托管模式</button>
</div>

// examples/guard-react18/normal/src/pages/Home.tsx
import React from 'react'
import { useHistory } from 'react-router-dom'

export default function Home() {
  const history = useHistory()

  const toEmbed = () => history.push('/embed')
  const toJump = () => history.push('/jump')

  return (
    <div>
      <div style={{ marginBottom: '20px' }} onClick={toEmbed}>
        <button className='authing-button'>嵌入模式 - 普通形态</button>
      </div>
      <div>
        <button className='authing-button' onClick={toJump}>托管模式</button>
      </div>
    </div>
  )
}
