// examples/guard-react/modal/src/pages/Home.tsx
import React from 'react'
import { useHistory } from 'react-router-dom'

export default function Home() {
  const history = useHistory()

  const toEmbed = () => history.push('/embed')

  return (
    <div>
      <div style={{ marginBottom: '20px' }} onClick={toEmbed}>
        <button>内嵌模式 - 模态框形态</button>
      </div>
    </div>
  )
}

// examples/guard-vue3/modal/src/views/Home.vue
<template>
  <div class="home-container">
    <button class="authing-button" @click="toEmbed">内嵌模式 - 模态框形态</button>
  </div>
</template>

<script lang="ts" setup>
import { useRouter } from 'vue-router'

const router = useRouter()

const toEmbed = () => {
  router.push({
    path: '/embed'
  })
}
</script>
