// examples/guard/src/pages/Callback.tsx
import React, { useEffect } from 'react'

import { Guard } from '@authing/guard'

import { guardOptions } from '../config'

export default function Callback() {
  const handleCallback = async () => {
    const guard = new Guard(guardOptions)

    console.log('guard: ', guard)

    await guard.handleRedirectCallback()

    // ******** 使用 replace ********
    window.location.replace('/personal')
  }

  useEffect(() => {
    handleCallback()
  })

  return <div>This is Callback page</div>
}

// examples/guard-vue2/src/views/Callback.vue
<template>
  <div class="callback-container">
    <div>{{ message }}</div>
  </div>
</template>

<script scoped>

export default {
  data () {
    return {
      message: 'This is callback page ~',
      loginState: ''
    }
  },
  mounted () {
    if (this.$authing.isRedirectCallback()) {
      console.log("redirect");
      this.$authing.handleRedirectCallback().then((res) => {
        this.loginState = res;
        window.location.replace("/");
      });
    } else {
      this.getLoginState();
    }
  },
  methods: {
    async getLoginState() {
      const state = await this.$authing.getLoginState();
      this.loginState = state;
    }
  }
}
</script>
